name: Test
on:
  pull_request:
  push:

jobs:
  test:
    name: Test Linux
    runs-on: ["ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v2
      - run: |
        make && make test
